### ISSUE TITLE
Crash in Airing Title Detail

### ISSUE THREAD

**Issue by srvrguy** [AnimeNeko/Atarashii#444]
Using AniList as provider, you can get the application to crash by going to the "Airing" section, then tapping on a title. Crash log follows:
```
E/AndroidRuntime(15701): FATAL EXCEPTION: main
E/AndroidRuntime(15701): Process: net.somethingdreadful.MAL, PID: 15701
E/AndroidRuntime(15701): java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = net.somethingdreadful.MAL.api.response.Anime)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeSerializable(Parcel.java:1394)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeValue(Parcel.java:1341)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeList(Parcel.java:717)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeValue(Parcel.java:1290)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
E/AndroidRuntime(15701): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(15701): 	at android.os.Bundle.writeToParcel(Bundle.java:1034)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeBundle(Parcel.java:669)
E/AndroidRuntime(15701): 	at android.app.FragmentState.writeToParcel(Fragment.java:139)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeTypedArray(Parcel.java:1197)
E/AndroidRuntime(15701): 	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeParcelable(Parcel.java:1363)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeValue(Parcel.java:1268)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
E/AndroidRuntime(15701): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(15701): 	at android.os.Bundle.writeToParcel(Bundle.java:1034)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeBundle(Parcel.java:669)
E/AndroidRuntime(15701): 	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2925)
E/AndroidRuntime(15701): 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3299)
E/AndroidRuntime(15701): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15701): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15701): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15701): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime(15701): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15701): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15701): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(15701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(15701): Caused by: java.io.NotSerializableException: net.somethingdreadful.MAL.api.response.Anime$Airing
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
E/AndroidRuntime(15701): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
E/AndroidRuntime(15701): 	at android.os.Parcel.writeSerializable(Parcel.java:1389)
E/AndroidRuntime(15701): 	... 26 more
```

**Comment by ratan12** [comment]
Does the bug still exists?

**Comment by ratan12** [comment]
"Airing" section doesn't exists anymore
